import { useTheme } from "next-themes";
import Head from "next/head";
import { useEffect, useState } from "react";
import Nav from "../components/Nav/Nav";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-monts">
        <h1>This IS THE DASHBOARD</h1>
      </main>
    </>
  );
}
