import Experience from '@/components/Experience/Experience';
import Projects from '@/components/Projects/Projects';
import { useTheme } from 'next-themes';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Arrow from '../../public/Arrow.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>I&apos;m André! Nice to finally meet!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-monts grid gap-12 grid-cols-2 grid-rows-3 h-full justify-between">
        <div className="about-section border-[0.5px] border-gray-400 h-full rounded-2xl px-4 py-4 bg-white bg-opacity-5 drop-shadow-md overflow-hidden">
          <div className="title">
            <h2 className="font-semibold mb-4">
              <Link href={'/about'} className="flex gap-3">
                ABOUT <Image src={Arrow} alt="arrow" />
              </Link>
            </h2>
          </div>
          <p>
            I’m a seasoned full stack developer with 6 years of experience
            designing and developing websites and software applications...
          </p>
          <Link href={'/about'} className="button text-center">
            Learn More
          </Link>
        </div>
        <Experience />
        <Projects />
        <div className="contact-section  border-[0.5px] border-gray-400 h-full rounded-2xl px-4 py-4 bg-white bg-opacity-5 drop-shadow-2xl">
          <div className="title">
            <h2 className="font-semibold mb-4">
              <Link href={'/contact'} className="flex gap-3">
                CONTACT <Image src={Arrow} alt="arrow" />
              </Link>
            </h2>
          </div>
          <p>
            Have a comment, question, request? Reach out! I’d love you here from
            you!
          </p>
          <Link href={'/contact'} className="button block text-center w-full">
            GET IN TOUCH!
          </Link>
        </div>
      </main>
    </>
  );
}
