import Experience from "@/components/Experience/Experience";
import Projects from "@/components/Projects/Projects";
import { useTheme } from "next-themes";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import Arrow from "../../public/Arrow.svg";
import Button from "@/components/Button/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>I&apos;m André! Nice to finally meet!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-monts lg:grid gap-4 lg:grid-cols-2 lg:grid-rows-3 h-auto min-h-[85vh] justify-between flex flex-col mb-20 lg:mb-0">
        <div className="about-section border-[0.5px] border-gray-400 rounded-2xl px-4 py-4 bg-white bg-opacity-5 drop-shadow-md  h-full">
          <div className="title">
            <h2 className="font-semibold mb-4">
              <Link href={"/about"} className="flex gap-3">
                ABOUT <Image src={Arrow} alt="arrow" />
              </Link>
            </h2>
          </div>
          <p>
            I’m a seasoned full stack developer with 6 years of experience
            designing and developing websites and software applications...
          </p>
          <Button href="/about" linkText="Learn More" />
        </div>
        <Experience />
        <Projects />
        <div className="contact-section  border-[0.5px] border-gray-400 h-full rounded-2xl px-4 py-4 bg-white bg-opacity-5 drop-shadow-2xl">
          <div className="title">
            <h2 className="font-semibold mb-4">
              <Link href={"/contact"} className="flex gap-3">
                CONTACT <Image src={Arrow} alt="arrow" />
              </Link>
            </h2>
          </div>
          <p>
            Have a comment, question, request? Reach out! I’d love you here from
            you!
          </p>
          <Button href="/contact" linkText="Get In Touch" />
        </div>
      </main>
    </>
  );
}
