import React from 'react';
import Head from 'next/head';

const FileHead = ({ title }: { title: string }) => {
  console.log(title);
  return (
    <Head>
      <title>{title} | A Guy Named André</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  );
};

export default FileHead;
