import React from 'react'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Layout from '../components/Layout'
// const { motion } = require('framer-motion')
import '../styles/globals.scss'

const pageAnimation = {
    pageInitial: {
        opacity: 0,
    },
    pageAnimate: {
        opacity: 1,
    }
}


function MyApp({ Component, pageProps, router }) {
  return <>
    <Head>
        <title>I&apos;m André! It&apos;s Nice To Meet You!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Spartan:wght@400;500;700&display=swap" rel="stylesheet" />

    </Head>
    <Header />
    <div initial="pageInitial" animate="pageAnimate" variants={pageAnimation} key={router.route}>
        <Component {...pageProps} />
    </div>
  <Footer />
  </>
}

export default MyApp
