import React from 'react'
import Head from 'next/head'
import Script from 'next/script'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Layout from '../components/Layout'
const { motion } = require('framer-motion')
import '../styles/globals.scss'

const pageAnimation = {
    pageInitial: {
        opacity: 0,
    },
    pageAnimate: {
        opacity: 1,
    }
}

function MyApp({ Component, pageProps, router }) {
  return <>
  <Script
    strategy='lazyOnload'
    src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`} />
    <Script
        strategy='lazyOnload'>
            {
                `window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', ${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS});`
            }
        </Script>
    <Head>
        <title>I&apos;m André! It&apos;s Nice To Meet You!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Spartan:wght@400;500;700&display=swap" rel="stylesheet" />
    </Head>
    <Header />
    <motion.div initial="pageInitial" animate="pageAnimate" variants={pageAnimation} key={router.route}>
        <Component {...pageProps} />
    </motion.div>
  <Footer />
  </>
}

export default MyApp
