import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
// const { motion } = require('framer-motion')
import { buttonContainer, containerAnimation, item } from '../components/framer-animations/homepage'

export default function Home() {
  return (
      <>
        <Head>
            <title>I&apos;m André! It&apos;s Nice To Meet You!</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/assets/favicon.ico" />
        </Head>
        <div variants={containerAnimation} initial="hidden" animate="visible" className="flex center column full-height homepage">
            <h1 variants={item}>Husband. Father. Software Developer.</h1>
            <div variants={buttonContainer} className="transparent-btn-wrapper flex mobile-column">
                <div variants={item} className="transparent-btn"><Link href="/projects#about">About</Link></div>
                <div variants={item} className="transparent-btn"><Link href="/projects">Projects</Link></div>
                <div variants={item} className="transparent-btn"><Link href="#">Contact</Link></div>
            </div>
        </div>
    </>
  )
}
